project:
  type: website
  output-dir: docs

website:
  title: "Jörgs Testblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kantel
      - icon: mastodon
        href: https://mastodon.social/@kantel
format:
  html:
    theme: litera
    css: styles.css

editor: visual

