project:
  type: website
  output-dir: docs

website:
  title: "Der Schockwellenreiter"
  site-url: https://kantel.github.io/
  description: "Schockwellenreiter"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kantel
      - icon: mastodon
        href: https://mastodon.social/@kantel
      - icon: rss
        href: index.xml
format:
  html:
    theme: litera
    css: styles.css
    include-in-header: "js/matomo.js"

editor: visual

