project:
  type: website
  output-dir: docs

website:
  title: "Der Schockwellenreiter"
  site-url: https://kantel.github.io/
  description: "Schockwellenreiter"
  favicon: "favicon.ico"
  navbar:
    right:
      - about.qmd
      - impressum.qmd
      - icon: github
        href: https://github.com/kantel/kantel.github.io
      - icon: mastodon
        href: https://mastodon.social/@kantel
      - icon: rss
        href: index.xml
format:
  html:
    code-line-numbers: true
    theme: litera
    css: styles.css
    link-external-icon: false
    include-in-header: "js/goatcounter.js"

editor: source

